### ISSUE TITLE
Misleading version number

### ISSUE THREAD

**Issue by ageorge95** [greenbtc/greenbtc-blockchain#4]
Hi,

Please do not mislead people into thinking that this is a fork of chia v1.6.1 !

This is just another fork of silicoin, with very little customizations on top of the upstream code (1 parameter name refactor and a handful of parameter values).

**Comment by greenbtc** [comment]
Please update to the latest version

**Comment by ageorge95** [comment]
Hi, Thanks for the response. It is a bit late though 😁 This Issue was created 2+ years ago.

I will just close it as it is irrelevant now.
